/**
 * Golden anti-drift tests: the consolidated TS quantum math must reproduce the
 * verified Python backend (src/qforge/engine/bloch_math.py) exactly.
 *
 * Fixtures are generated by `scripts/gen_quantum_golden.py` and live in
 * `./golden/bloch_golden.json`. They contain, per state, the statevector in the
 * frontend convention (qubit 0 = MSB) and the backend-computed per-qubit Bloch
 * vectors, per-qubit purity Tr(rho^2), and two-qubit Pauli correlators.
 *
 * This test proves FE math == BE math. If a value disagrees, do NOT loosen the
 * tolerance: regenerate the fixture and fix the convention/bug.
 *
 * The `asym_product3` fixture is an asymmetric product state |0>(x)|+>(x)|+i>
 * whose three qubits have distinct Bloch vectors; it verifies that the backend
 * and frontend agree on per-qubit *index* ordering (qubit 0 = MSB on both
 * sides), which the permutation-symmetric Bell/GHZ/W/cluster states cannot.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, it, expect } from "vitest";
import {
  type Complex,
  stateVectorToBloch,
  purity,
  expectZ,
  expectZZ,
} from "../index";

const TOL = 6; // toBeCloseTo digits => |a-b| < 5e-7 (~1e-6)

interface GoldenQubit {
  qubit_index: number;
  bloch: { rx: number; ry: number; rz: number };
  purity: number;
}
interface GoldenPair {
  qubit_i: number;
  qubit_j: number;
  correlators: { zi: number; iz: number; zz: number; xx: number; yy: number };
}
interface GoldenState {
  id: string;
  description: string;
  num_qubits: number;
  statevector: [number, number][];
  qubits: GoldenQubit[];
  pairs: GoldenPair[];
}
interface GoldenDoc {
  schema_version: string;
  generated_by: string;
  source: string;
  convention: string;
  states: GoldenState[];
}

const here = dirname(fileURLToPath(import.meta.url));
const golden = JSON.parse(
  readFileSync(join(here, "golden", "bloch_golden.json"), "utf-8"),
) as GoldenDoc;

function toComplexSv(sv: [number, number][]): Complex[] {
  return sv.map(([re, im]) => [re, im] as Complex);
}

describe("golden: FE quantum math reproduces backend bloch_math", () => {
  it("fixture file is present and non-empty", () => {
    expect(golden.schema_version).toBe("1.0");
    expect(golden.states.length).toBeGreaterThan(0);
  });

  for (const state of golden.states) {
    describe(`${state.id} — ${state.description}`, () => {
      const sv = toComplexSv(state.statevector);
      const n = state.num_qubits;

      it("per-qubit Bloch vectors match backend", () => {
        for (const q of state.qubits) {
          const b = stateVectorToBloch(sv, q.qubit_index, n);
          expect(b.rx).toBeCloseTo(q.bloch.rx, TOL);
          expect(b.ry).toBeCloseTo(q.bloch.ry, TOL);
          expect(b.rz).toBeCloseTo(q.bloch.rz, TOL);
        }
      });

      it("per-qubit purity Tr(rho^2) matches backend", () => {
        for (const q of state.qubits) {
          expect(purity(sv, q.qubit_index, n)).toBeCloseTo(q.purity, TOL);
        }
      });

      it("two-qubit Z-basis correlators (zi, iz, zz) match backend", () => {
        for (const p of state.pairs) {
          // zi = <Z_i (x) I> = <Z_i>; iz = <I (x) Z_j> = <Z_j>; zz = <Z_i Z_j>
          expect(expectZ(sv, p.qubit_i, n)).toBeCloseTo(p.correlators.zi, TOL);
          expect(expectZ(sv, p.qubit_j, n)).toBeCloseTo(p.correlators.iz, TOL);
          expect(expectZZ(sv, p.qubit_i, p.qubit_j, n)).toBeCloseTo(
            p.correlators.zz,
            TOL,
          );
        }
      });
    });
  }
});
